services:
  - type: worker
    name: video-downloader-bot
    env: python
    region: oregon
    plan: free
    buildCommand: bash build.sh
    startCommand: python -m app.main
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.0"
